module Config
    APPWRITE_ENDPOINT = ENV['APPWRITE_ENDPOINT']
    APPWRITE_API_KEY = ENV['APPWRITE_API_KEY']
    APPWRITE_FUNCTION_PROJECT_ID = ENV['APPWRITE_FUNCTION_PROJECT_ID']
    APPWRITE_DATABASE_ID = ENV['APPWRITE_DATABASE_ID']
    APPWRITE_COLLECTION_ID = ENV['APPWRITE_COLLECTION_ID']
    MEILISEARCH_ENDPOINT = ENV['MEILISEARCH_ENDPOINT']
    MEILISEARCH_INDEX_NAME = ENV['MEILISEARCH_INDEX_NAME']
    MEILISEARCH_ADMIN_API_KEY = ENV['MEILISEARCH_ADMIN_API_KEY']
    MEILISEARCH_SEARCH_API_KEY = ENV['MEILISEARCH_SEARCH_API_KEY']
  end
  