source "https://rubygems.org"

gem 'json', '>= 2.7.6', '< 3.0.0'
gem 'dotenv', '>= 2.8.1', '< 3.0.0'
gem 'digest', '>= 3.2.1', '< 4.0.0'
gem 'jwt', '>= 3.2.0', '< 4.0.0'
gem 'httparty', '>= 0.21.0', '< 0.22.0'