name: generate_pdf
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  dart_appwrite: ^13.0.0
  faker_dart: ^0.2.2
  pdf: ^3.11.3
  shelf: ^1.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
