name: "Generate README markdown table"

on:
  push:
    branches:
      - main
jobs:
  readme-generator:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Prepare repository
      uses: actions/checkout@v4

    - name: Prepare Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run table generator
      run: | 
        cd .github/workflows/markdown-table-workflow
        npm install
        node index.js

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "docs: update README table"

